export const hadithList = [
    {
        "id": 1,
        "title": "Amal Tergantung Niat",
        "arabic": "عَنْ أَمِيرِ المُؤْمِنِيْنَ أَبِي حَفْصٍ عُمَرَ بْنِ الخَطَّابِ رَضِيَ اللَّهُ عَنْهُ قَالَ: سَمِعْتُ رَسُولَ اللهِ ﷺ يَقُولُ: «إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإنَّمَا لِكُلِّ امْرِىءٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلى اللهِ وَرَسُوْلِهِ فَهِجْرتُهُ إِلَى اللهِ وَرَسُوُلِهِ، وَمَنْ كَانَتْ هِجْرَتُهُ لِدُنْيَا يُصِيْبُهَا أَوِ امْرأَةٍ يَنْكِحُهَا فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إلَيْهِ»\nرَوَاهُ إِمَامَا المُحَدِّثِيْنَ أَبُوْ عَبْدِ اللهِ مُحَمَّدِ بْنِ إِسْمَاعِيْلَ بْنِ إِبْرَاهِيْمَ بْنِ المُغِيْرَةِ بْنِ بَرْدِزْبَهَ البُخَارِيُّ، وَأَبُوْ الْحُسَيْنِ مُسْلِمُ بْنُ الْحَجَّاجِ بْنِ مُسْلِمٍ الْقُشَيْرِيُّ النَّيْسَابُوْرِيُّ، فِي صَحِيْحَيْهِمَا اللَّذَيْنِ هُمَا أَصَحُّ الكُتُبِ المُصَنَّفَةِ.",
        "translation": "Dari Amirul Mukminin Abu Hafsh ‘Umar bin Khaththab Radhiyallahu ‘Anhu berkata: aku mendengar Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Sesungguhnya amal itu tergantung dengan niatnya dan setiap orang akan mendapatkan sesuai dengan niatnya. Maka, barangsiapa yang hijrahnya kepada Allah dan Rasul-Nya maka hijrahnya kepada Allah dan Rasul-Nya, dan barangsiapa yang hijrahnya kepada dunia yang ingin diraih atau wanita yang ingin dinikahi maka hijrahnya kepada apa yang dia berhijrah kepadanya.”\nDiriwayatkan dua imam ahli hadits: Abu Abdillah Muhammad bin Ismail bin Ibrahim bin Al-Mughirah bin Bardizbah Al-Bukhari dan Abul Husain Muslim bin Hajjaj bin Muslim Al-Qushairi An-Naisaburi di kedua kitab Shahihnya yang merupakan dua kitab paling shahih yang pernah disusun. (HR. Al-Bukhari no. 1 dan Muslim no. 1907)"
    },
    {
        "id": 2,
        "title": "Pengertian Islam, Iman, dan Ihsan",
        "arabic": "عَنْ عُمَرَ رَضِيَ اللهُ عَنْهُ أَيْضاً قَالَ: بَيْنَمَا نَحْنُ عِنْدَ رَسُولِ اللهِ ﷺ ذَاتَ يَوْمٍ، إَذْ طَلَعَ عَلَيْناَ رَجُلٌ شَدِيْدُ بَيَاضِ الثِّيَابِ، شَدِيْدُ سَوَادِ الشَّعْرِ، لاَ يُرَى عَلَيْهِ أَثَرُ السَّفَرِ، وَلاَ يَعْرِفُهُ مِنَّا أَحَدٌ حَتَّى جَلَسَ إلَى النَّبِيِّ ﷺ فَأَسْنَدَ رُكْبَتَيْهِ إلَى رُكْبَتَيْهِ وَوَضَعَ كَفَّيْهِ عَلَى فَخِذَيْهِ وَقَالَ: يَا مُحَمَّدُ أَخْبِرْنِي عَنِ الإِسْلاَمِ!\nفَقَالَ رَسُولُ اللهِ ﷺ: «الإِسْلاَمُ أَنْ تَشْهَدَ أَنْ لاَ إلَهَ إِلاَّ اللهُ وَأَنَّ مُحَمَّداً رَسُولُ اللهِ، وَتُقِيْمَ الصَّلاَةَ، وَتُؤْتِيَ الزَّكَاةَ، وَتَصُوْمَ رَمَضَانَ، وَتَحُجَّ البَيْتَ إِنِ اسْتَطَعْتَ إِلَيْهِ سَبِيْلاً»\nقَالَ: صَدَقْتَ. فَعجِبْنَا لَهُ يَسْأَلُهُ وَيُصَدِّقُهُ، قَالَ: فَأَخْبِرْنِي عَنِ الإِيْمَانِ! قَالَ: «أَنْ تُؤْمِنَ بِاللهِ، وَمَلاِئِكَتِهِ، وَكُتُبِهِ، وَرُسُلِهِ، وَالْيَومِ الآخِرِ، وَتُؤْمِنَ بِالقَدَرِ خَيْرِهِ وَشَرِّهِ»\nقَالَ: صَدَقْتَ، قَالَ فَأَخْبِرْنِي عَنِ الإِحْسَانِ! قَالَ: «أَنْ تَعْبُدَ اللهَ كَأَنَّكَ تَرَاهُ، فَإِنْ لَمْ تَكُنْ تَرَاهُ فَإِنَّهُ يَرَاكَ» قَالَ: فَأَخْبِرْنِي عَنِ السَّاعَةِ! قَالَ: «مَا الْمَسْؤُوْلُ عَنْهَا بِأَعْلَمَ مِنَ السَّائِلِ» قَالَ: فَأخْبِرْنِي عَنْ أَمَارَاتِها! قَالَ: «أَنْ تَلِدَ الأَمَةُ رَبَّتَهَا، وَأَنْ تَرَى الحُفَاةَ العُرَاةَ العَالَةَ رِعَاءَ الشَّاءِ يَتَطَاوَلُوْنَ فِي البُنْيَانِ» ثُمَّ انْطَلَقَ فَلَبِثْتُ مَلِيًّا، ثُمَّ قَالَ: «يَا عُمَرُ! أَتَدْرِي مَنِ السَّائِلُ؟» قُلْتُ: اللهُ وَرَسُوْلُهُ أَعْلَمُ، قَالَ: «فَإِنَّهُ جِبْرِيْلُ أَتَاكُمْ يُعَلِّمُكُمْ دِيْنَكُمْ» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari ‘Umar Radhiyallahu ‘Anhu juga, ia berkata: pada suatu hari kami berada di sisi Rasulullah Shallallahu ‘Alaihi wa Sallam, tiba-tiba datang kepada kami seseorang yang sangat putih pakaiannya, sangat hitam rambutnya, tidak nampak kalau sedang bepergian, dan tidak ada seorang pun dari kami yang mengenalnya. Kemudian dia duduk menghadap Nabi Shallallahu ‘Alaihi wa Sallam lalu menyandarkan lututnya kepada lutut beliau, dan meletakkan kedua telapak tangannya di atas paha beliau. Dia bertanya, “Ya Muhammad! Kabarkan kepadaku tentang Islam.” Maka, Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Islam adalah Anda bersyahadat lâ ilâha illâllâh dan muhammadur rasûlûllâh, menegakkan shalat, menunaikan zakat, berpuasa Ramadhan, dan berhaji ke Baitullah jika Anda mampu menempuh jalannya.” Lelaki itu berkata, “Engkau benar.” Kami heran terhadapnya, dia yang bertanya sekaligus membenarkannya. Lelaki itu bekata lagi, “Kabarkanlah kepadaku tentang iman!” Beliau menjawab, “Anda beriman kepada Allah, para Malaikat-Nya, Kitab-Kitab-Nya, para Rasul-Nya, hari Akhir, dan Anda beriman kepada takdir yang baik maupun yang buruk.” Lelaki itu menjawab, “Engkau benar.” Dia bekata lagi, “Kabarkan kepadaku tentang ihsan!” Beliau menjawab, “Anda menyembah Allah seolah-olah melihatnya. Jika Anda tidak bisa melihat-Nya, maka sesungguhnya Dia melihat Anda.” Dia berkata lagi, “Kabarkan kepadaku tentang hari Kiamat!” Beliau menjawab, “Tidaklah yang ditanya lebih tahu daripada yang bertanya.” Dia berkata lagi, “Kabarkan kepadaku tentang tanda-tandanya.” Beliau menjawab, “Jika seorang budak wanita melahirkan majikannya, dan jika Anda melihat orang yang tidak beralas kaki, tidak berpakaian, miskin, dan penggembala kambing saling bermegah-megahan meninggikan bangunan.”\nKemudian lelaki itu pergi. Aku diam sejenak lalu beliau bersabda, “Hai ‘Umar! Tahukah kamu siapa yang bertanya itu?”  Aku menjawab, “Allah dan Rasul-Nya lebih tahu.” Beliau bersabda, “Sesungguhnya dia Jibril yang datang kepada kalian untuk mengajarkan agama kalian.” (HR. Muslim no. 8)"
    },
    {
        "id": 3,
        "title": "Rukun Islam",
        "arabic": "عَنْ أَبِي عَبْدِ الرَّحْمَنِ عَبْدِ اللهِ بْنِ عُمَرَ بْنِ الخَطَّابِ رَضِيَ اللهُ عَنْهُمَا قَالَ: سَمِعْتُ النَّبِيَّ ﷺ يَقُوْلُ: «بُنِيَ الإِسْلاَمُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لاَ إِلَهَ إِلاَّ اللهُ وَأَنَّ مُحَمَّدًا رَسُوْلُ اللهِ، وَإِقَامِ الصَّلاَةِ، وَإِيْتَاءِ الزَّكَاةِ، وَحَجِّ البَيْتِ، وَصَوْمِ رَمَضَانَ» رَوَاهُ البُخَارِي وَمُسْلِمٌ.",
        "translation": "Dari Abu Abdirrahman Abdullah bin ‘Umar bin Khaththab Radhiyallahu ‘Anhuma, ia berkata: aku mendengar Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Islam dibagun di atas lima hal: syahadat lâ ilâha illâllâh dan muhammadur rasûlûllâh, menegakkan shalat, menunaikan zakat, haji ke Baitullah, dan puasa Ramadhan.” (HR. Al-Bukhari no. 8 dan Muslim no. 16)"
    },
    {
        "id": 4,
        "title": "Proses Penciptaan Manusia",
        "arabic": "عَنْ أَبِي عَبْدِ الرَّحْمَنِ عَبْدِ اللهِ بْنِ مَسْعُوْدٍ رَضِيَ اللهُ عَنْهُ، قَالَ: حَدَّثَنَا رَسُوْلُ اللهِ ﷺ وَهُوَ الصَّادِقُ المَصْدُوْقُ: «إِنَّ أَحَدَكُمْ يُجْمَعُ خَلْقُهُ فِيْ بَطْنِ أُمِّهِ أَرْبَعِيْنَ يَوْماً، ثُمَّ يَكُوْنُ عَلَقَةً مِثْلَ ذَلِكَ، ثُمَّ يَكُوْنُ مُضْغَةً مِثْلَ ذَلِكَ، ثُمَّ يُرْسَلُ إِلَيْهِ المَلَكُ، فَيَنفُخُ فِيْهِ الرُّوْحَ وَيُؤْمَرُ بِأَرْبَعِ كَلِمَاتٍ: بِكَتْبِ رِزْقِهِ وَأَجَلِهِ وَعَمَلِهِ وَشَقِيٌّ أَوْ سَعِيْدٍ.\nفَوَالَّذِي لاَ إِلَهَ غَيْرُهُ! إِنَّ أَحَدَكُمْ لَيَعْمَلُ بِعَمَلِ أَهْلِ الجَنَّةِ حَتَّى مَا يَكُوْنُ بَيْنَهُ وَبَيْنَهَا إِلَّا ذِرَاعٌ، فَيَسْبِقُ عَلَيْهِ الكِتَابُ فَيَعْمَلُ بِعَمَلِ أَهْلِ النَّارِ فَيَدْخُلُهَا.\nوَإِنَّ أَحَدَكُمْ لَيَعْمَلُ بِعَمَلِ أَهْلِ النَّارِ حَتَّى مَايَكُونُ بَيْنَهُ وَبَيْنَهَا إِلَّا ذِرَاعٌ فَيَسْبِقُ عَلَيْهِ الكِتَابُ فَيَعْمَلُ بِعَمَلِ أَهْلِ الجَنَّةِ فَيَدْخُلُهَا» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Abu Abdirrahman Abdullah bin Mas’ud Radhiyallahu ‘Anhu, ia berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam telah menceritakan kepada kami dan beliau seorang yang jujur lagi diakui kejujurannya, “Sesungguhnya seorang dari kalian dikumpulkan penciptaannya di perut ibunya selama empat puluh hari, kemudian menjadi segumpal darah selama itu pula, kemudian menjadi segumpal daging selama itu pula, kemudian diutus seorang Malaikat kepadanya untuk meniupkan ruh padanya, dan diperintahkan empat kalimat: menulis rezekinya, ajalnya, amalnya, dan celaka atau bahagia. Demi Allah yang tidak ada sesembahan yang berhak disembah selain Dia, sesungguhnya seorang dari kalian benar-benar beramal dengan amal penghuni Surga hingga jarak antaranya dan Surga hanya sejengkal, lalu takdir mendahuluinya, lalu dia beramal dengan amal penduduk Neraka lalu ia pun memasukinya. Dan sesungguhnya seorang dari kalian benar-benar  beramal dengan amal penduduk Neraka hingga jarak antaranya dengan Neraka hanya sejengkal, lalu takdir mendahuluinya, lalu ia beramal dengan amal penduduk Surga, maka ia pun memasukinya.” (HR. Al-Bukhari no. 3208 dan Muslim no. 2643)"
    },
    {
        "id": 5,
        "title": "Bahaya Bid’ah",
        "arabic": "عَنْ أُمِّ المُؤْمِنِيْنَ أُمِّ عَبْدِ اللهِ عَائِشَةَ رَضِيَ اللهُ عَنْهَا، قَالَتْ: قَالَ رَسُوْلُ اللهِ ﷺ: «مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.\nوَفِي رِوَايَةٍ لِمُسْلِمٍ: «مَنْ عَمِلَ عَمَلاً لَيْسَ عَلَيْهِ أَمْرُنَا فَهُوَ رَدٌّ»",
        "translation": "Dari Ummul Mukminin Ummu Abdillah ‘Aisyah Radhiyallahu ‘Anha, ia berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Barangsiapa yang mengada-mengada dalam urusan kami ini yang bukan bagian darinya, maka ia tertolak.” (HR. Al-Bukhari no. 2697 dan Muslim no. 1718)\nDalam riwayat Muslim, “Barangsiapa yang beramal tanpa ada perintahnya dari kami, maka amal itu tertolak.” (HR. Muslim no. 1718)"
    },
    {
        "id": 6,
        "title": "Halal dan Haram",
        "arabic": "عَنْ أَبِي عَبْدِ اللهِ النُّعْمَانِ بْنِ بَشِيْرٍ رَضِيَ اللهُ عَنْهُمَا، قَالَ: سَمِعْتُ رَسُوْلَ اللهِ ﷺ يَقُوْلُ: «إِنَّ الحَلَالَ بَيِّنٌ، وَإِنَّ الحَرَامَ بَيِّنٌ، وَبَيْنَهُمَا مُشْتَبِهَاتٌ لاَ يَعْلَمُهُنَّ كَثِيْرٌ مِنَ النَّاسِ، فَمَنِ اتَّقَى الشُّبُهَاتِ اِسْتَبْرَأَ لِدِيْنِهِ وعِرْضِهِ، وَمَنْ وَقَعَ فِي الشُّبُهَاتِ وَقَعَ فِي الحَرَامِ كَالرَّاعِي يَرْعَى حَوْلَ الحِمَى يُوشِكُ أَنْ يَقَعَ فِيْهِ.\nأَلَا وَإِنَّ لِكُلِّ مَلِكٍ حِمًى. أَلَا وَإِنَّ حِمَى اللهِ مَحَارِمُهُ.\nأَلَا وَإِنَّ فِي الجَسَدِ مُضْغَةً، إِذَا صَلَحَتْ صَلَحَ الجَسَدُ كُلُّهُ وَإِذَا فَسَدَتْ فَسَدَ الجَسَدُ كُلُّهُ، أَلَا وَهِيَ القَلْبُ» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Abu Abdillah An-Nu’man bin Basyir Radhiyallahu ‘Anhuma berkata: aku mendengar Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, ”Sesungguhnya yang halal telah jelas dan yang haram telah jelas, dan di antara keduanya ada hal-hal yang samar yang tidak diketahui kebanyakan manusia. Barangsiapa menjaga diri dari hal yang samar (syubhat), sungguh dia telah memelihara agama dan kehormatannya, dan barangsiapa yang terjatuh pada yang syubhat, akan terjatuh pada yang haram, seperti penggembala yang menggembala di sekitar tanah larangan yang suatu saat akan memasukinya. Ketahuilah, sesungguhnya setiap raja memiliki batas larangan. Ketahuilah batas larangan Allah adalah hal yang diharamkan-Nya. Ketahuilah, di dalam tubuh ada segumpal daging, jika baik maka baik pula seluruh tubuh, tetapi jika buruk maka buruk pula seluruh tubuh. Ketahuilah, segumpal daging itu adalah hati.” (HR. Al-Bukhari no. 52 dan Muslim no. 1599)"
    },
    {
        "id": 7,
        "title": "Agama adalah Nasihat",
        "arabic": "عَنْ أَبِي رُقَيَّةَ تَمِيْمِ بْنِ أَوْسٍ الدَّارِيِّ رَضِيَ اللهُ عَنْهُ، أَنَّ النَّبِيَّ ﷺ قَالَ: «الدِّيْنُ النَّصِيْحَةُ» قُلْنَا: لِمَنْ؟ قَالَ: «للهِ، وَلِكِتَابِهِ، وَلِرَسُوْلِهِ، وَلِأَئِمَّةِ المُسْلِمِيْنَ، وَعَامَّتِهِمْ» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu Ruqayyah Tamim bin Aus Ad-Dari Radhiyallahu ‘Anhu bahwa Nabi Shallallahu ‘Alaihi wa Sallam bersabda, “Agama adalah nasihat.” Kami bertanya, “Untuk siapa?” Beliau menjawab, “Untuk Allah, Kitab-Nya, Rasul-Nya, dan pemimpin kaum Muslimin dan orang awamnya.” (HR. Muslim no. 55)"
    },
    {
        "id": 8,
        "title": "Haram Darah Seorang Muslim",
        "arabic": "عَنِ ابْنِ عُمَرَ رَضِيَ اللهُ عَنْهُمَا، أَنَّ رَسُوْلَ اللهِ ﷺ قَالَ: «أُمِرْتُ أَنْ أُقَاتِلَ النَّاسَ حَتَّى يَشْهَدُوا أَنْ لاَ إِلَهَ إِلاَّ اللهُ وَأَنَّ مُحَمَّدًا رَسُوْلُ اللهِ، وَيُقِيْمُوْا الصَّلَاةَ، وَيُؤْتُوا الزَّكَاةَ، فَإِذَا فَعَلُوا ذَلِكَ عَصَمُوا مِنِّي دِمَاءَهُمْ وَأَمْوَالَهُمْ إِلاَّ بِحَقِّ الإِسْلَامِ وَحِسَابُهُمْ عَلَى اللهِ تَعَالَى» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Ibnu Umar bahwa Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Aku diperintahkan untuk memerangi manusia hingga mereka bersyahadat lâ ilâha illâllâh dan muhammadur rasûlûllâh, menegakkan shalat, dan membayar zakat. Jika mereka melaksanakan hal tersebut, maka mereka telah memelihara harta dan darah mereka dariku kecuali dengan hak Islam, dan hisab mereka diserahkan kepada Allah Ta’ala.” (HR. Al-Bukhari no. 25 dan Muslim no. 22)"
    },
    {
        "id": 9,
        "title": "Menjalankan Perintah Semampunya",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ عَبْدِ الرَّحْمَنِ بْنِ صَخْرٍ رَضِيَ اللهُ عَنْهُ، قَالَ: سَمِعْتُ رَسُوْلَ اللهِ ﷺ يَقُوْلُ: «مَا نَهَيْتُكُمْ عَنْهُ فَاجْتَنِبُوهُ، وَمَا أَمَرْتُكُمْ بِهِ فَافْعَلُوا مِنْهُ مَا اسْتَطَعْتُمْ، فَإِنَّمَا أَهْلَكَ الَّذِيْنَ مِنْ قَبْلِكُمْ كَثْرَةُ مَسَائِلِهِمْ وَاخْتِلافُهُمْ عَلَى أَنْبِيَائِهِمْ» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu, ia berkata: aku mendengar Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Apa yang aku larang bagi kalian maka jauhilah, dan apa yang aku perintahkan kepada kalian maka kerjakan semampu kalian. Sesungguhnya yang membinasakan orang-orang sebelum kalian adalah banyak bertanya dan menyelisihi para Nabi.” (HR. Al-Bukhari no. 7288 dan Muslim no. 1337)"
    },
    {
        "id": 10,
        "title": "Meninggalkan yang Haram",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ، قَالَ: قَالَ رَسُوْلُ اللهِ ﷺ: «إِنَّ اللهَ تَعَالَى طَيِّبٌ لاَ يَقْبَلُ إِلاَّ طَيِّباً، وَإِنَّ اللهَ أَمَرَ المُؤْمِنِيْنَ بِمَا أَمَرَ بِهِ المُرْسَلِيْنَ فَقَالَ تَعَالَى: ﴿يَا أَيُّهَا الرُّسُلُ كُلُوا مِنَ الطَّيِّبَاتِ وَاعْمَلُوا صَالِحاً﴾ [المؤمنون: ٥١] وَقَالَ تَعَالَى: ﴿يَا أَيُّهَا الَّذِيْنَ آمَنُوا كُلُوا مِنْ طَيِّبَاتِ مَا رَزَقْنَاكُمْ﴾ [البقرة: ١٧٢]\nثُمَّ ذَكَرَ: الرَّجُلَ يُطِيْلُ السَّفَرَ أَشْعَثَ أَغْبَرَ، يَمُدُّ يَدَيْهِ إِلَى السَّمَاءِ: يَا رَبِّ! يَا رَبِّ! وَمَطْعَمُهُ حَرَامٌ، وَمَشْرَبُهُ حَرَامٌ، وَمَلْبَسُهُ حَرَامٌ، وَغُذِيَ بِالحَرَامِ، فَأَنَّى يُسْتَجَابُ لِذَلِكَ؟!» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu, berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam pernah bersabda, “Sesungguhnya Allah itu baik, tidak mau menerima kecuali yang baik. Dan sesungguhnya Allah telah memerintahkan kepada orang-orang Mukmin seperti yang telah diperintahkan kepada para Rasul, Allah berfirman, ‘Wahai para Rasul makanlah dari segala sesuatu yang baik dan kerjakanlah amal shalih.’ [QS. Al-Mukminun [23]: 51] Dan Dia berfirman, ‘Wahai orang-orang yang beriman, makanlah dari apa-apa yang baik yang telah Kami berikan kepadamu.’ [QS. Al-Baqarah [2]: 172] Kemudian beliau menceritakan kisah seorang laki-laki yang melakukan perjalanan jauh, rambutnya kusut dan berdebu. Dia menengadahkan kedua tangannya ke langit seraya berdoa, ‘Wahai Rabb-ku, wahai Rabb-ku,’ sedangkan makanannya haram, minumannya haram, pakaiannya haram, dan (perutnya) dikenyangkan dengan makanan haram, maka bagaimana mungkin do’anya dikabulkan.” (HR. Muslim no. 1015)"
    },
    {
        "id": 11,
        "title": "Tinggalkan Apa yang Meragukan",
        "arabic": "عَنْ أَبِي مُحَمَّدٍ الحَسَنِ بْنِ عَلِيِّ بْنِ أَبِي طَالِبٍ سِبْطِ رَسُولِ اللهِ ﷺ وَرَيْحَانَتِهِ رَضِيَ اللهُ عَنْهُمَا، قَالَ: حَفِظْتُ مِنْ رَسُوْلِ اللهِ ﷺ: «دَعْ مَا يَرِيْبُكَ إِلَى مَا لاَ يَرِيْبُكَ» رَوَاهُ التِّرْمِذِيُّ وَالنَّسَائِيُّ وَقَالَ التِّرْمِذِيُّ: حَدِيْثٌ حَسَنٌ صَحِيْحٌ.",
        "translation": "Dari Abu Muhammad Al-Hasan bin Ali bin Abi Thalib cucu Rasulullah Shallallahu ‘Alaihi wa Sallam dan kesayangannya, ia berkata: aku hafal dari Rasulullah Shallallahu ‘Alaihi wa Sallam, “Tinggalkan apa yang meragukanmu kepada apa yang tidak meragukanmu.” (HR. At-Tirmidzi no. 2518, An-Nasa`i VIII/327, dan At-Tirmidzi berkata, “Hadits hasan shahih.”)"
    },
    {
        "id": 12,
        "title": "Tinggalkan Apa yang Tidak Berguna",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ، قَالَ: قَالَ رَسُوْلُ اللهِ ﷺ: «مِنْ حُسْنِ إِسْلَامِ المَرْءِ تَرْكُهُ مَا لاَ يَعْنِيْهِ» حَدِيْثٌ حَسَنٌ، رَوَاهُ التِّرْمِذِيُّ وَغَيْرُهُ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu, ia berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Di antara bagusnya ke-Islaman seseorang adalah meninggalkan apa yang tidak berguna baginya.” (Hadits hasan, HR. At-Tirmidzi no. 2317 dan selainnya)"
    },
    {
        "id": 13,
        "title": "Di Antara Kesempurnaan Iman",
        "arabic": "عَنْ أَبِي حَمْزَةَ أَنَسِ بْنِ مَالِكٍ رَضِيَ اللهُ عَنْهُ خَادِمِ رَسُوْلِ اللهِ ﷺ، عَنِ النَّبِيِّ ﷺ قَالَ: «لاَ يُؤمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيْهِ مَا يُحِبُّ لِنَفْسِهِ» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Abu Hamzah Anas bin Malik Radhiyallahu ‘Anhu pelayan Rasulullah Shallallahu ‘Alaihi wa Sallam, dari Nabi Shallallahu ‘Alaihi wa Sallam bersabda, “Tidak beriman (dengan sempurna) salah seorang dari kalian hingga dia mencintai untuk saudaranya apa yang dia cintai untuk dirinya sendiri.” (HR. Al-Bukhari no. 13 dan Muslim no. 45)"
    },
    {
        "id": 14,
        "title": "Sebab-Sebab Darah Ditumpahkan",
        "arabic": "عنِ ابْنِ مَسْعُودٍ رَضِيَ اللهُ عَنْهُ، قَالَ: قَالَ رَسُولُ اللهِ ﷺ: «لَا يَحِلُّ دَمُ امْرِئٍ مُسْلِمٍ إِلاَّ بِإِحْدَى ثَلَاثٍ: الثَّيِّبُ الزَّانِي، وَالنَّفْسُ بِالنَّفْسِ، وَالتَّارِكُ لِدِيْنِهِ المُفَارِقُ لِلْجَمَاعَةِ» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Ibnu Mas’ud Radhiyallahu ‘Anhu, ia berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Tidak halal darah seorang Muslim kecuali karena salah satu dari tiga hal: orang yang berzina padahal sudah menikah, membunuh jiwa, dan orang yang meninggalkan agamanya lagi memisahkan diri dari jamaah.” (HR. Al-Bukhari no. 6878 dan Muslim no. 1676)"
    },
    {
        "id": 15,
        "title": "Di Antara Akhlak Seorang Mukmin",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ، أَنَّ رَسُولَ اللهِ ﷺ قَالَ: «مَنْ كَانَ يُؤمِنُ بِاللهِ وَاليَوْمِ الآخِرِ فَلْيَقُلْ خَيْراً أَوْ لِيَصْمُتْ، وَمَنْ كَانَ يُؤمِنُ بِاللهِ وَاليَوْمِ الآخِرِ فَلْيُكْرِمْ جَارَهُ، ومَنْ كَانَ يُؤمِنُ بِاللهِ واليَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu, bahwa Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Barangsiapa yang beriman kepada Allah dan hari Akhir, maka berkatalah yang baik atau diam saja. Barangsiapa yang beriman kepada Allah dan hari Akhir, maka memuliakanlah tetangganya. Barangsiapa yang beriman kepada Allah dan hari Akhir, maka memuliakanlah tamunya.” (HR. Al-Bukhari no. 6018 dan Muslim no. 47)"
    },
    {
        "id": 16,
        "title": "Jangan Marah",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ، أَنَّ رَجُلاً قَالَ لِلنَّبِيِّ ﷺ: أَوْصِنِيْ! قَالَ: «لاَ تَغْضَبْ» فَرَدَّدَ مِرَارًا وَقَالَ: «لاَ تَغْضَبْ» رَوَاهُ البُخَارِيُّ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu bahwa seseorang berkata kepada Nabi Shallallahu ‘Alaihi wa Sallam, “Berilah aku nasihat!” Beliau menjawab, “Jangan marah.” Dia mengulangi beberapa kali dan beliau tetap menjawab, “Jangan marah.” (HR. Al-Bukhari no. 6116)"
    },
    {
        "id": 17,
        "title": "Berbuat Baik Atas Segala Sesuatu",
        "arabic": "عَنْ أَبِي يَعْلَى شَدَّادِ بْنِ أَوْسٍ رَضِيَ اللهُ عَنْهُ، عَنْ رَسُوْلِ اللهِ ﷺ قَالَ: «إِنَّ اللهَ كَتَبَ الإِحْسَانَ عَلَى كُلِّ شَيءٍ، فَإِذَا قَتَلْتُمْ فَأَحْسِنُوا القِتْلَةَ، وَإِذَا ذَبَحْتُمْ فَأَحْسِنُوا الذِّبْحَةَ، وَلْيُحِدَّ أَحَدُكُمْ شَفْرَتَهُ، وَلْيُرِحْ ذَبِيْحَتَهُ» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu Ya’la Syaddad bin Aus Radhiyallahu ‘Anhu, dari Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Sesungguhnya Allah menetapkan untuk berbuat baik atas segala sesuatu. Maka, apabila kalian membunuh membunuhlah dengan cara yang baik, dan apabila kalian menyembelih menyembelilah dengan baik pula. Hendaklah salah seorang dari kalian menajamkan pisaunya dan mempermudah penyembelihan.” (HR. Muslim no. 1955)"
    },
    {
        "id": 18,
        "title": "Bertakwalah Kepada Allah",
        "arabic": "عَنْ أَبِي ذَرٍّ جُنْدُبِ بْنِ جُنَادَةَ وَأَبِي عَبْدِ الرَّحْمَنِ مُعَاذِ بْنِ جَبَلٍ رَضِيَ اللهُ عَنْهُمَا، عَنْ رَسُولِ اللهِ ﷺ قَالَ: «اِتَّقِ اللهَ حَيْثُمَا كُنْتَ، وَأَتْبِعِ السَّيِّئَةَ الحَسَنَةَ تَمْحُهَا، وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ» رَوَاهُ التِّرْمِذِيُّ وَقَالَ: حَدِيْثٌ حَسَنٌ، وَفِي بَعْضِ النُّسَخِ: حَسَنٌ صَحِيحٌ.",
        "translation": "Dari Abu Dzar Jundub bin Junadah dan Abu Abdirrahman Muadz bin Jabal Radhiyallahu ‘Anhuma, dari Rasulullah Shallallahu ‘Alaihi wa Sallam, beliau bersabda, “Bertaqwalah kepada Allah di mana saja kamu berada, dan iringilah keburukan dengan kebaikan maka ia akan menghapusnya, dan pergauilah manusia dengan akhlak yang baik.” (HR. At-Tirmidzi no. 1987 dan berkata, “Hadits hasan,” dalam redaksi lain, “Hasan shahih.”)"
    },
    {
        "id": 19,
        "title": "Jagalah Allah, Maka Dia akan Menjagamu",
        "arabic": "عَنْ أَبِي العَبَّاسِ عَبْدِ اللهِ بْنِ عَبَّاسٍ رَضِيَ اللهُ عَنْهُمَا، قَالَ: كُنْتُ خَلْفَ النَّبِيِّ ﷺ يَوْماً فَقَالَ: «يَا غُلاَمُ إِنّي أُعَلِّمُكَ كَلِمَاتٍ: اِحْفَظِ اللهَ يَحفَظْكَ، اِحْفَظِ اللهَ تَجِدْهُ تُجَاهَكَ، إِذَا سَأَلْتَ فَاسْأَلِ اللهَ، وَإِذَا اسْتَعَنْتَ فَاسْتَعِنْ بِاللهِ، وَاعْلَمْ أَنَّ الأُمَّةَ لَوِ اجْتَمَعَتْ عَلَى أَنْ يَنْفَعُوكَ بِشَيْءٍ لَمْ يَنْفَعُوكَ إِلَّا بِشَيْءٍ قَدْ كَتَبَهُ اللهُ لَكَ، وَإِنِ اجْتَمَعُوا عَلَى أَنْ يَضُرُّوكَ بِشَيْءٍ لَمْ يَضُرُّوكَ إِلَّا بِشَيْءٍ قَدْ كَتَبَهُ اللهُ عَلَيْكَ، رُفِعَتِ الأَقْلَامُ، وَجَفَّتِ الصُّحُفُ» رَوَاهُ التِّرْمِذِيُّ وَقَالَ: حَدِيْثٌ حَسَنٌ صَحِيْحٌ.\nوَفِي رِوَايَةِ غَيْرِ التِّرْمِذِيِّ: «اِحْفَظِ اللهَ تَجِدْهُ أَمَامَكَ، تَعَرَّفْ إِلَى اللهِ فِي الرَّخَاءِ يَعْرِفْكَ فِي الشِّدَّةِ، وَاعْلَمْ أَنَّ مَا أَخْطَأَكَ لَمْ يَكُنْ لِيُصِيْبَكَ، وَمَا أَصَابَكَ لَمْ يَكُنْ لِيُخْطِئَكَ، وَاعْلَمْ أنَّ النَّصْرَ مَعَ الصَّبْرِ، وَأَنَّ الفَرَجَ مَعَ الكَرْبِ، وَأَنَّ مَعَ العُسْرِ يُسْراً»",
        "translation": "Dari Abul Abbas Abdullah bin Abbas Radhiyallahu ‘Anhu, ia berkata: aku pernah di belakang Nabi Shallallahu ‘Alaihi wa Sallam pada suatu hari, lalu beliau bersabda, “Hai anak kecil! Sesungguhnya aku akan mengajarimu satu kalimat, ‘Jagalah Allah, maka Allah akan menjagamu. Jagalah Allah, maka kamu akan mendapati-Nya di hadapanmu. Apabila kamu meminta, mintalah kepada Allah. Apabila kamu meminta pertolongan, maka mintalah pertolongan kepada Allah. Ketahuilah! Seandainya umat manusia bersatu untuk memberikan suatu manfaat kepadamu, mereka tidak akan bisa memberimu manfaat kecuali sesuatu yang telah Allah tulis untukmu, dan seandainya mereka bersatu untuk menimpakan suatu bahaya kepadamu, niscaya mereka tidak akan bisa menimpakan bahaya kepadamu kecuali sesuatu yang telah ditulis atasmu. Pena telah diangkat dan lembaran telah kering.” (HR. At-Tirmidzi no. 2516 dan berkata, “Hadits hasan shahih.”)\nDalam riwayat selain At-Tirmidzi, “Jagalah Allah, maka kamu akan mendapati-Nya di hadapanmu. Kenalilah Allah saat lapang, maka Dia akan mengenalmu saat susah. Ketahuilah! Apa yang meleset bagimu tidak akan menimpamu, dan apa yang menimpamu tidak akan meleset bagimu. Ketahuilah! Sesungguhnya pertolongan itu bersama kesabaran, sesungguhnya kelapangan itu bersama kesempitan, dan sesungguhnya bersama kesusahan itu ada kemudahan.” (HR. Ahmad 1/293, 303, 307-308)"
    },
    {
        "id": 20,
        "title": "Malu Akhlak Para Nabi",
        "arabic": "عَنْ أَبِي مَسْعُوْدٍ عُقبَةَ بْنِ عَمْرٍو الأَنْصَارِيِّ البَدْرِيِّ رَضِيَ اللهُ عَنْهُ، قَالَ: قَالَ رَسُوْلُ اللهِ ﷺ: «إِنَّ مِمَّا أَدْرَكَ النَّاسُ مِنْ كَلاَمِ النُّبُوَّةِ الأُوْلَى إِذَا لَمْ تَسْتَحْيِ فَاصْنَعْ مَا شِئْتَ» رَوَاهُ البُخَارِيُّ.",
        "translation": "Dari Abu Mas’ud Uqbah bin Amr Al-Anshari Al-Badri Radhiyallahu ‘Anhu, berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam pernah bersabda, “Sesungguhnya sebagian ajaran yang masih dikenal umat manusia dari perkataan para Nabi terdahulu adalah: ‘Bila kamu tidak punya rasa malu, berbuatlah sesukamu.’” (HR. Al-Bukhari no. 3483)"
    },
    {
        "id": 21,
        "title": "Katakanlah, “Aku beriman kepada Allah!”",
        "arabic": "عَنْ أَبِي عَمْرٍو -وَقِيْلَ أَبِي عَمْرَةَ- سُفْيَانَ بْنِ عَبْدِ اللهِ رَضِيَ اللهُ عَنْهُ، قَالَ: قُلْتُ: يَا رَسُوْلَ اللهِ! قُلْ لِي فِي الإِسْلَامِ قَوْلاً لاَ أَسْأَلُ عَنْهُ أَحَداً غَيْرَكَ؟ قَالَ: «قُلْ آمَنْتُ باللهِ ثُمَّ اسْتَقِمْ» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu ‘Amr –ada yang berpendapat Abu Amroh– Sufyan bin Abdillah Ats-Tsaqafi Radhiyallahu ‘Anhu, ia berkata: aku berkata, “Wahai Rasulullah! Katakanlah kepadaku dalam Islam sebuah ucapan yang tidak aku tanyakan lagi kepada selain Anda.” Beliau menjawab, “Katakanlah, ‘Aku beriman kepada Allah!’ kemudian istiqomahlah.’” (HR. Muslim 38)"
    },
    {
        "id": 22,
        "title": "Amalan yang Memasukkan ke Surga",
        "arabic": "عَنْ أَبِي عَبْدِ اللهِ جَابِرِ بْنِ عَبْدِ اللهِ الأَنْصَارِيِّ رَضِيَ اللهُ عَنْهُمَا: أَنَّ رَجُلاً سَأَلَ النَّبِيَّ ﷺ فَقَالَ: أَرَأَيْتَ إِذَا صَلَّيْتُ المَكْتُوبَاتِ، وَصُمْتُ رَمَضَانَ، وَأَحْلَلْتُ الحَلاَلَ، وَحَرَّمْتُ الحَرَامَ، وَلَمْ أَزِدْ عَلَى ذَلِكَ شَيْئاً أَأَدْخُلُ الجَنَّةَ؟ قَالَ: «نَعَمْ» رَوَاهُ مُسْلِمٌ.\nوَمَعْنَى «حَرَّمْتُ الحَرَامَ»: اِجْتَنَبْتُهُ. وَمَعْنَى «أَحْلَلْتُ الحَلَالَ»: فَعَلْتُهُ مُعْتَقِدًا حِلَّهُ.",
        "translation": "Dari Abu Abdillah Jabir bin Abdillah Al-Anshari Radhiyallahu ‘Anhuma bahwa seseorang bertanya kepada Rasulullah Shallallahu ‘Alaihi wa Sallam seraya berkata, “Bagaimana pendapat Anda jika aku shalat wajib, berpuasa Ramadhan, menghalalkan yang halal, mengharamkan yang haram, dan aku tidak menambah selain itu, apakah aku akan masuk Surga?” Beliau menjawab, “Ya.” (HR. Muslim no. 15)\nMakna “aku mengharamkan yang haram” adalah “aku menjauhinya”, dan makna “aku menghalalkan yang halal” adalah “aku mengerjakannya dengan menyakini kehalalannya”."
    },
    {
        "id": 23,
        "title": "Setiap Manusia Berbuat",
        "arabic": "عَنْ أَبِي مَالِكٍ الحَارِثِ بْنِ عَاصِمٍ الأَشْعَرِيِّ رَضِيَ اللهُ عَنْهُ، قَالَ: قَالَ رَسُولُ اللهِ ﷺ: «الطُّهُورُ شَطْرُ الإِيْمَانِ، والحَمْدُ للهِ تَمْلأُ المِيْزَانَ، وَسُبْحَانَ اللهِ والحَمْدُ للهِ تَمْلآنِ -أَو تَمْلأُ- مَا بَيْنَ السَّمَاءِ وَالأَرْضِ، وَالصَّلاةُ نُوْرٌ، وَالصَّدَقَةُ بُرْهَانٌ، وَالصَّبْرُ ضِيَاءٌ، وَالقُرْآنُ حُجَّةٌ لَكَ أَو عَلَيْكَ، كُلُّ النَّاسِ يَغْدُو فَبَائِعٌ نَفْسَهُ فَمُعْتِقُهَا أَوْ مُوْبِقُهَا» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu Malik Al-Harits bin Ashim Al-Asy’ari Radhiyallahu ‘Anhu berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Bersuci adalah sebagian dari iman. Alhamdulillah memenuhi timbangan. Subhanallah dan Alhamdulillah memenuhi –atau keduanya memenuhi– antara langit dan bumi. Shalat adalah cahanya, sedekah adalah bukti, sabar adalah lentera, dan Al-Qur`an adalah hujjah yang membelamu atau yang melawanmu. Setiap manusia memasuki waktu pagi dalam keadaan menjual dirinya, lalu dia memerdekakannya atau membinasakannya.” (HR. Muslim. 223)"
    },
    {
        "id": 24,
        "title": "Janganlah Kalian Saling Menzhalimi",
        "arabic": "عَنْ أَبِي ذَرٍّ رَضِيَ اللهُ عَنْهُ، عَنِ النَّبِيِّ ﷺ فِيْمَا رَوَى عَنِ اللهِ عَزَّ وَجَلَّ، أَنَّهُ قَالَ: «يَا عِبَادِيْ! إِنِّيْ حَرَّمْتُ الظُّلْمَ عَلَى نَفْسِيْ وَجَعَلْتُهُ بَيْنَكُمْ مُحَرَّماً فَلَا تَظَالَمُوْا. يَا عِبَادِيْ! كُلُّكُمْ ضَالٌّ إِلاَّ مَنْ هَدَيْتُهُ فَاسْتَهْدُوْنِي أَهْدِكُمْ. يَا عِبَادِيْ! كُلُّكُمْ جَائِعٌ إِلاَّ مَنْ أَطْعَمْتُهُ فاَسْتَطْعِمُونِي أُطْعِمْكُمْ. يَا عِبَادِيْ! كُلُّكُمْ عَارٍ إِلاَّ مَنْ كَسَوْتُهُ فَاسْتَكْسُوْنِيْ أَكْسُكُمْ. يَا عِبَادِيْ! إِنَّكُمْ تُخْطِئُوْنَ بِاللَّيْلِ وَالنَّهَارِ وَأَنَا أَغْفِرُ الذُّنُوْبَ جَمِيْعاً فَاسْتَغْفِرُوْنِيْ أَغْفِرْ لَكُمْ. يَا عِبَادِيْ! إِنَّكُمْ لَنْ تَبْلُغُوْا ضَرِّيْ فَتَضُرُّوْنِيْ وَلَنْ تَبْلُغُوْا نَفْعِيْ فَتَنْفَعُوْنِيْ.\nيَا عِبَادِيْ! لَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإِنْسَكُمْ وَجِنَّكُمْ كَانُوْا عَلَى أَتْقَى قَلْبِ رَجُلٍ وَاحِدٍ مِنْكُمْ مَا زَادَ ذَلِكَ فِيْ مُلْكِيْ شَيْئًا.\nيَا عِبَادِيْ! لَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإِنْسَكُمْ وَجِنَّكُمْ كَانُوْا عَلَى أَفْجَرِ قَلْبِ رَجُلٍ وَاحِدٍ مِنْكُمْ مَا نَقَصَ ذَلِكَ مِنْ مُلْكِيْ شَيْئَاً.\nيَا عِبَادِيْ! لَوْ أنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإنْسَكُمْ وَجِنَّكُمْ قَامُوْا فِيْ صَعِيْدٍ وَاحِدٍ فَسَأَلُوْنِيْ فَأَعْطَيْتُ كُلَّ وَاحِدٍ مَسْأَلَتَهُ مَا نَقَصَ ذَلِكَ مِمَّا عِنْدِيْ إِلاَّ كَمَا يَنْقُصُ المِخْيَطُ إِذَا أُدْخِلَ البَحْرَ.\nيَا عِبَادِيْ! إِنَّمَا هِيَ أَعْمَالُكُمْ أُحْصِيْهَا لَكُمْ ثُمَّ أُوَفِّيْكُمْ إِيَّاهَا، فَمَنْ وَجَدَ خَيْراً فَلْيَحْمَدِ اللهَ، وَمَنْ وَجَدَ غَيْرَ ذَلِكَ فَلاَ يَلُوْمَنَّ إِلاَّ نَفْسَهُ» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu Dzar Al-Ghifari Radhiyallahu ‘Anhu, dari Nabi Shallallahu ‘Alaihi wa Sallam tentang hadits yang diriwayatkan dari Rabb-nya bahwa Dia berfirman, “Hai hamba-hamba-Ku! Sesungguhnya Aku telah mengharamkan kezhaliman atas diri-Ku dan menjadikannya haram di antara kalian, maka janganlah kalian saling menzhalimi. Hai hamba-hamba-Ku! Setiap kalian adalah orang yang sesat kecuali siapa yang Aku beri petunjuk, maka mintalah petunjuk kepada-Ku niscaya Aku beri kalian petunjuk. Hai hamba-hamba-Ku! Setiap kalian adalah lapar kecuali siapa yang Aku beri makan, maka mintalah makan kepada-Ku, pasti Aku beri kalian makan. Hai hamba-hamba-Ku! Setiap kalian adalah telanjang kecuali siapa yang Aku beri pakaian, maka mintalah kepada-Ku pakaian, pasti Aku akan beri kalian pakaian. Hai hamba-hamba-Ku! Sesungguhnya kalian melakukan dosa di malam dan siang hari sementara Aku mengampuni dosa-dosa semuanya, maka mintalah ampun kepada-Ku, pasti Aku ampuni kalian. Hai hamba-hamba-Ku! Sesungguhnya kalian tidak akan mampu menimpakan bahaya kepada-Ku, dan tidak akan mampu memberi manfaat kepada-Ku. Hai hamba-hamba-Ku! Seandainya yang paling awal dan terakhir dari kalian baik jin dan manusia semuanya berada pada hati yang paling bertakwa salah seorang dari kalian, tentu tidak akan menambah kerajaan-Ku sedikitpun. Hai hamba-hamba-Ku! Seandainya yang paling awal dan terakhir dari kalian baik jin dan manusia semuanya berada pada hati yang paling durhaka salah seorang dari kalian, tentu tidak akan mengurangi kerajaan-Ku sedikitpun. Hai hamba-hamba-Ku! Seandainya yang paling awal dan terakhir dari kalian baik jin dan manusia semuanya berada di atas satu bukit, lalu semuanya meminta kepada-Ku, lalu Aku beri semua permintaannya, maka hal itu tidak akan mengurangi sedikitpun apa yag ada di sisi-Ku, secuali sekedar seperti berkurangnya samudra jika jarum dimasukkan. Hai hamba-hamba-Ku! Sesungguhnya itu adalah amal-amal kalian yang Aku tulis untuk kalian kemudian Aku sempurnakan itu untuk kalian. Barangsiapa yang mendapati kebaikan, maka pujilah Allah, dan barangsiapa yang mendapati selain itu, maka janganlah mencela kecuali dirinya sendiri.” (HR. Muslim no. 2577)"
    },
    {
        "id": 25,
        "title": "Setiap Kebaikan adalah Sedekah",
        "arabic": "عَنْ أَبِي ذَرٍّ رَضِيَ اللهُ عَنْهُ أَيْضاً: أَنَّ نَاساً مِنْ أَصْحَابِ رَسُولِ اللهِ ﷺ قَالُوا لِلنَّبِيِّ ﷺ: يَارَسُولَ الله! ذَهَبَ أَهْلُ الدُّثُوْرِ بِالْأُجُوْرِ، يُصَلُّوْنَ كَمَا نُصَلِّي، وَيَصُوْمُوْنَ كَمَا نَصُوْمُ، وَيَتَصَدَّقُوْنَ بفُضُوْلِ أَمْوَالِهِمْ.\nقَالَ: «أَوَلَيْسَ قَدْ جَعَلَ اللهُ لَكُمْ مَا تَصَّدَّقُوْنَ؟ إِنَّ بِكُلِّ تَسْبِيْحَةٍ صَدَقَةً، وَكُلِّ تَكْبِيْرَةٍ صَدَقَةً، وَكُلِّ تَحْمِيْدَةٍ صَدَقَةً، وَكُلِّ تَهْلِيْلَةٍ صَدَقَةٌ، وَأَمْرٌ بِالِمَعْرُوْفِ صَدَقَةٌ، وَنَهْيٌ عَنْ مُنْكَرٍ صَدَقَةٌ، وَفِيْ بُضْعِ أَحَدِكُمْ صَدَقَةٌ»\nقَالُوا: يَا رَسُوْلَ اللهِ أَيَأْتِي أَحَدُنَا شَهْوَتَهُ وَيَكُوْنُ لَهُ فِيْهَا أَجْرٌ؟ قَالَ: «أَرَأَيْتُمْ لَوْ وَضَعَهَا فِي حَرَامٍ، أَكَانَ عَلَيْهِ وِزْرٌ؟ فَكَذَلِكَ إِذَا وَضَعَهَا فِي الحَلَالِ كَانَ لَهُ أَجْرٌ» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu Dzar Radhiyallahu ‘Anhu: sekelompok manusia dari Sahabat Rasulullah Shallallahu ‘Alaihi wa Sallam berkata kepada Nabi Shallallahu ‘Alaihi wa Sallam, “Ya Rasulullah! Orang-orang kaya memborong banyak pahala. Mereka shalat seperti kami shalat, mereka puasa seperti kami puasa, tetapi mereka bisa bersedekah dengan kelebihan harta mereka.” Beliau bersabda, “Bukankah Allah telah menjadikan untuk kalian apa yang bisa kalian sedekahkan? Sesungguhnya setiap tasbih adalah sedekah, setiap takbir adalah sedekah, setiap tahmid adalah sedekah, setiap tahlil adalah sedekah, setiap memerintah yang ma’ruf adalah sedekah, setiap melarang kemungkaran adalah sedekah, dan pada senggama kalian ada sedekahnya pula.” Mereka berkata, “Ya Rasulullah! Benarkah salah seorang dari kami melampiaskan syahwatnya lantas dia mendapat pahala?” Beliau menjawab, “Bagaimana menurut kalian, jika dia melampiaskannya pada yang haram, bukankah dia akan mendapat dosa? Begitu pula, jika dia melampiaskannya pada yang halal, maka dia mendapat pahala.” (HR. Muslim no. 1006)"
    },
    {
        "id": 26,
        "title": "Setiap Persendian Wajib Bersedekah",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ، قَالَ: قَالَ رَسُولُ اللهِ ﷺ: «كُلُّ سُلَامَى مِنَ النَّاسِ عَلَيْهِ صَدَقَةٌ كُلَّ يَوْمٍ تَطْلُعُ فِيْهِ الشَّمْسُ: تَعْدِلُ بَيْنَ الاثْنَيْنِ صَدَقَةٌ، وَتُعِيْنُ الرَّجُلَ في دَابَّتِهِ فَتَحْمِلُهُ عَلَيْهَا أَو تَرْفَعُ لَهُ عَلَيْهَا مَتَاعَهُ صَدَقَةٌ، وَالكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ، وَبِكُلِّ خُطْوَةٍ تَمْشِيْهَا إِلَى الصَّلَاةِ صَدَقَةٌ، وَتُمِيْطُ الأَذَى عَنِ الطَّرِيْقِ صَدَقَةٌ» رَوَاهُ البُخَارِيُّ وَمُsْلِمٌ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu, ia berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Setiap persendian manusia wajib bersedekah setiap hari di mana matahari terbit di hari itu: engkau mendamaikan antara dua orang adalah sedekah, engkau menolong seseorang untuk menaiki tunggangannya atau menggangkutkan barangnya ke atas tunggangannya adalah sedekah, kalimat yang baik adalah sedekah, setiap langkah yang engkau ayunkan menuju shalat adalah sedekah, engkau menyingkirkan gangguan dari jalan adalah sedekah.” (HR. Al-Bukhari no. 2707 dan Muslim no. 1009)"
    },
    {
        "id": 27,
        "title": "Kebaikan dan Dosa",
        "arabic": "عَنِ النَوَّاسِ بْنِ سَمْعَانَ رَضِيَ اللهُ عَنْهُ، عَنِ النَّبِيِّ ﷺ قَالَ: «البِرُّ حُسْنُ الْخُلُقِ، وَالْإِثْمُ مَا حَاكَ فِي نَفْسِكَ وَكَرِهْتَ أَنْ يَطَّلِعَ عَلَيْهِ النَّاسُ» رَوَاهُ مُسْلِمٌ.\nوَعَنْ وَابِصَةِ بْنِ مَعْبَدٍ رَضِيَ اللَّهُ عَنْهُ، قَالَ: أَتَيْتُ رَسُوْلَ اللَّهِ ﷺ، فَقَالَ: «جِئْتَ تَسْأَلُ عَنِ الْبِرِّ وَالْإِثْمِ؟» قُلْتُ: نَعَمْ! قَالَ: «اِسْتَفْتِ قَلْبَكَ. البِرُّ: مَا اطْمَأَنَّتْ إِلَيْهِ النَّفْسُ وَاطْمَأَنَّ اِلَيْهِ الْقَلْبُ. وَاْلإِثْمُ: مَا حَاكَ فِي النَّفْسِ وَتَرَدَّدَ فِي الصَّدْرِ، وَإِنْ أَفْتَاكَ النَّاسُ وَأَفْتَوْكَ»\nحَدِيْثٌ حَسَنٌ، رُوِّيْنَاهُ فِي مُسْنَدَيِ الْإِمَامَيْنِ أَحْمَدَ بْنِ حَنْبَلٍ وَالدَّارِمِيِّ بِإِسْنَادٍ حَسَنٍ.",
        "translation": "Dari An-Nawwas bin Sam’an Al-Anshari Radhiyallahu ‘Anhu, dari Nabi Shallallahu ‘Alaihi wa Sallam bersabda, “Kebaikan adalah akhlak yang mulia, dan dosa adalah apa yang membuat sesak dadamu dan engkau tidak suka orang lain mengetahuinya.” (HR. Muslim no. 2553)\nDari Wabishah bin Ma’bad Radhiyallahu ‘Anhu, ia berkata: aku datang kepada Rasulullah Shallallahu ‘Alaihi wa Sallam lalu beliau bersabda, “Engkau datang untuk bertanya tentang kebaikan dan dosa?” Aku menjawab, “Ya.” Beliau bersabda, “Tanyakan kepada dirimu sendiri. Kebaikan adalah what makes the soul calm and what makes the heart calm, and sin is what makes the soul constricted and hesitant in the chest, even if people give you a fatwa.” (Hadith hasan, we narrated it from Musnad Imam Ahmad bin Hanbal IV/228 and Musnad Ad-Darimi II/245-246 with a hasan isnad)"
    },
    {
        "id": 28,
        "title": "Mendengar dan Ta’at",
        "arabic": "عَنْ أَبِي نَجِيحٍ العِرْبَاضِ بْنِ سَارِيَةَ رَضِيَ اللهُ عَنْهُ، قَالَ: وَعَظَنَا رَسُولُ اللهِ ﷺ مَوْعِظَةً وَجِلَتْ مِنْهَا القُلُوبُ وَذَرَفَتْ مِنْهَا العُيُوْنُ، فَقُلْنَا: يَارَسُولَ اللهِ! كَأَنَّهَا مَوْعِظَةُ مُوَدِّعٍ فَأَوْصِنَا، قَالَ: «أُوْصِيْكُمْ بِتَقْوَى اللهِ عَزَّ وَجَلَّ وَالسَّمْعِ وَالطَّاعَةِ وَإِنْ تَأَمَّرَ عَلَيْكُمْ عَبْدٌ، فَإِنَّهُ مَنْ يَعِشْ مِنْكُمْ بَعْدِي فَسَيَرَى اخْتِلَافاً كَثِيراً، فَعَلَيْكُمْ بِسُنَّتِي وَسُنَّةِ الخُلَفَاءِ الرَّاشِدِيْنَ المَهْدِيِّيْنَ، عَضُّوْا عَلَيْهَا بِالنَّوَاجِذِ. وَإِيَّاكُمْ وَمُحْدَثَاتِ الأُمُورِ، فَإِنَّ كُلَّ بِدْعَةٍ ضَلَالَةٌ» رَوَاهُ أَبُوْ دَاوُدَ وَالتِّرْمِذِيُّ وَقَالَ: حَدِيْثٌ حَسَنٌ صَحِيحٌ.",
        "translation": "Dari Abu Najih Al-Irbadh bin Sariyah berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam menasihati kami dengan suatu nasihat yang menjadikan hati bergetar dan mata menangis, lalu kami berkata, “Ya Rasulullah! Seolah-olah ini adalah nasihat perpisahan, maka berilah kami wasiat.” Beliau menjawab, “Aku wasiatkan kepada kalian untuk bertakwa kepada Allah Azza wa Jalla, mendengar dan patuh meskipun yang menjadi pemimpin kalian seorang budak. Baransiapa yang hidup sepeninggalku, dia akan melihat banyak sekali perbedaan. Maka, hendaklah ia berpegang teguh kepada sunnahku dan sunnah Khulafaur Rasyidin yang terbimbing. Gigitlah ia dengan gigi geraham. Waspadalah kalian dari perkara yang baru dan setiap bid’ah adalah sesat.” (HR. Abu Dawud no. 4607 dan At-Tirmidzi no. 2676, dan dia berkata, “Hadits hasan shahih.”)"
    },
    {
        "id": 29,
        "title": "Pintu-Pintu Kebaikan",
        "arabic": "عَنْ مُعَاذِ بْنِ جَبَلٍ رَضِيَ اللهُ عَنْهُ قَالَ: قُلْتُ: يَا رَسُولَ اللهِ! أَخْبِرْنِي بِعَمَلٍ يُدْخِلُنِي الجَنَّةَ وَيُبَاعِدُنِي مِنَ النَّارِ. قَالَ: «لَقَدْ سَأَلْتَ عَنْ عَظِيْمٍ، وَإِنَّهُ لَيَسِيْرٌ عَلَى مَنْ يَسَّرَهُ اللهُ تَعَالَى عَلَيْهِ: تَعْبُدُ اللهَ لاَتُشْرِكُ بِهِ شَيْئَا، وَتُقِيْمُ الصَّلَاةَ، وَتُؤْتِي الزَّكَاةَ، وَتَصُومُ رَمَضَانَ، وَتَحُجُّ البَيْتَ»\nثُمَّ قَالَ: «أَلاَ أَدُلُّكَ عَلَى أَبْوَابِ الخَيْرِ؟ الصَّوْمُ جُنَّةٌ، وَالصَّدَقَةُ تُطْفِئُ الخَطِيْئَةَ كَمَا يُطْفِئُ المَاءُ النَّارَ، وَصَلَاةُ الرَّجُلِ فِي جَوْفِ اللَّيْلِ» ثُمَّ تَلَا :  ﴿تَتَجَافَى جُنُوبُهُمْ عَنِ الْمَضَاجِعِ﴾ حَتَّى بَلَغَ: ﴿يَعْلَمُونَ﴾ [السجدة: ١٦-١٧]\nثُمَّ قَالَ: «أَلَا أُخْبِرُكَ بِرَأْسِ الأَمْرِ وَعَمُودِهِ وَذِرْوَةِ سَنَامِهِ؟» قُلْتُ: بَلَى يَارَسُولَ اللهِ! قَالَ: «رَأْسُ الأَمْرِ الإِسْلَامُ وَعَمُودُهُ الصَّلَاةُ وَذِرْوَةُ سَنَامِهِ الجِهَادُ»\nثُمَّ قَالَ: «أَلَا أُخْبِرُكَ بِمِلاَكِ ذَلِكَ كُلِّهِ؟» قُلْتُ: بَلَى يَارَسُولَ اللهِ! فَأَخَذَ بِلِسَانِهِ وَقَالَ: «كُفَّ عَلَيْكَ هَذَا!» قُلْتُ: يَانَبِيَّ اللهِ! وَإِنَّا لَمُؤَاخَذُونَ بِمَا نَتَكَلَّمُ بِهِ؟ فَقَالَ: «ثَكِلَتْكَ أُمُّكَ! وَهَلْ يَكُبُّ النَّاسَ فِي النَّارِ عَلَى وُجُوهِهِمْ -أَوْ عَلَى مَنَاخِرِهِمْ- إِلاَّ حَصَائِدُ أَلسِنَتِهِمْ؟» رَوَاهُ التِّرْمِذِيُّ وَقَالَ: حَدِيْثٌ حَسَنٌ صَحِيحٌ.",
        "translation": "Dari Mu’adz bin Jabal Radhiyallahu ‘Anhu, ia berkata: aku berkata, “Wahai Rasulullah, beritahu aku amal yang bisa memasukkanku ke dalam Surga dan menjauhkanku dari Neraka.” Beliau bersabda, “Engkau telah bertanya tentang masalah yang besar. Namun, itu adalah perkara yang mudah bagi siapa yang dimudahkan oleh Allah: engkau menyembah Allah jangan menyekutukan-Nya dengan apapun, mendirikan shalat, mengeluarkan zakat, berpuasa Ramadhan, dan haji ke Baitullah.” Kemudian beliau bersabda, “Maukah kamu aku tunjukkan pintu-pintu kebajikan? Puasa adalah perisai, sedekah memadamkan dosa sebagaimana air memadamkan api, dan shalatnya seseorang di tengah malam.” Kemudian beliau membaca ayat, “Lambung mereka jauh dari tempat tidurnya ...” hingga firman-Nya, “Sebagai balasan terhadap apa yang telah mereka kerjakan.” (QS. As-Sajdah [32]: 16-17) Kemudian beliau bersabda kembali, “Maukah kamu kuberitahu pangkal agama, tiangnya, dan puncak tertingginya?” Aku menjawab, “Mau, wahai Rasulullah.” Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Pokok urusan adalah Islam, tiangnya adalah shalat, dan puncak tertingginya adalah jihad.” Kemudian beliau melanjutkan, “Maukah kamu kuberitahu tentang kendali bagi semua itu?” Saya menjawab, “Mau, wahai Rasulullah.” Beliau lalu memegang lidahnya dan bersabda, “Jagalah ini.” Saya berkata, “Wahai Nabi Allah, apakah kita akan disiksa karena ucapan-ucapan kita?” Beliau menjawab, “Celaka kamu. Bukankah banyak dari kalangan manusia yang tersungkur ke dalam api Neraka dengan mukanya terlebih dahulu –dalam riwayat lain: dengan lehernya terlebih dahulu– itu gara-gara buah ucapan lisannya?” (HR. At-Tirmidzi no. 2616 dan berkata, “Hadits ini hasan shahih.”)"
    },
    {
        "id": 30,
        "title": "Batasan-Batasan Allah",
        "arabic": "عَنْ أَبِي ثَعْلَبَةَ الخُشَنِيِّ جُرثُومِ بْنِ نَاشِرٍ رَضِيَ اللهُ عَنْهُ، عَنْ رَسُولِ اللهِ ﷺ قَالَ: «إِنَّ اللهَ فَرَضَ فَرَائِضَ فَلَا تُضَيِّعُوهَا، وَحَدَّ حُدُوْداً فَلَا تَعْتَدُوهَا وَحَرَّمَ أَشْيَاءَ فَلَا تَنْتَهِكُوهَا، وَسَكَتَ عَنْ أَشْيَاءَ رَحْمَةً لَكُمْ غَيْرَ نِسْيَانٍ فَلَا تَبْحَثُوا عَنْهَا» حِدِيْثٌ حَسَنٌ رَوَاهُ الدَّارَقُطْنِيُّ وَغَيْرُهُ.",
        "translation": "Dari Abu Tsa'labah Al-Khusyanni Jurtsum bin Nasyir Radhiyallahu ‘Anhu, dari Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Sesungguhnya Allah telah menetapkan beberapa kewajiban maka janganlah engkau menyepelekannya, dan Dia telah menentukan batasan-batasan maka janganlah engkau melanggarnya, dan Dia telah pula mengharamkan beberapa hal maka janganlah engkau jatuh ke dalamnya. Dia juga mendiamkan beberapa hal –karena kasih sayangnya kepada kalian bukannya lupa– maka janganlah engkau membahasnya.” (Hadits hasan, HR. Ad-Daruquthni no. 4316 dan selainnya)"
    },
    {
        "id": 31,
        "title": "Buah Zuhud",
        "arabic": "عَنْ أَبِي العَبَّاسِ سَعْدِ بْنِ سَهْلٍ السَّاعِدِيِّ رَضِيَ اللهُ عَنْهُ، قَالَ: جَاءَ رَجُلٌ إِلَى النَّبِيِّ ﷺ فَقَالَ: يَا رَسُولَ اللهِ: دُلَّنِي عَلَى عَمَلٍ إِذَا عَمِلْتُهُ أَحَبَّنِيَ اللهُ وَأَحَبَّنِيَ النَّاسُ؟ فَقَالَ: «اِزْهَدْ فِي الدُّنْيَا يُحِبَّكَ اللهُ، وَازْهَدْ فِيْمَا عِنْدَ النَّاسِ يُحِبَّكَ النَّاسُ» حَدِيْثٌ حَسَنٌ رَوَاهُ ابْنُ مَاجَهْ وَغَيْرُهُ بِأَسَانِيْدَ حَسَنَةٍ.",
        "translation": "Dari Abul Abbas Sa’ad bin Sahl As-Sa’idi Radhiyallahu ‘Anhu berkata: seseorang datang kepada Nabi Shallallahu ‘Alaihi wa Sallam lalu berkata, “Wahai Rasulullah! Tunjukkanlah kepadaku suatu amal yang apabila aku kerjakan, maka Allah mencintaiku dan manusia juga mencintaiku!” Beliau menjawab, “Zuhudlah di dunia maka Allah akan mencintaimu, dan zuhudlah dari apa yang ada di tangan manusia maka manusia akan mencintaimu.” (Hadits hasan, HR. Ibnu Majah no. 4102 dan selainnya dengan sanad  yang hasan)"
    },
    {
        "id": 32,
        "title": "Tidak Ada Bahaya dan Tidak Boleh Membahayakan",
        "arabic": "عَنْ أَبِي سَعِيْدٍ سَعْدِ بْنِ مَالِكِ بْنِ سِنَانٍ الخُدْرِيِّ رَضِيَ اللهُ عَنْهُ أَنَّ رَسُوْلَ اللهِ ﷺ قَالَ: «لاَ ضَرَرَ وَلاَ ضِرَارَ» حَدِيْثٌ حَسَنٌ. رَوَاهُ ابْنُ مَاجَهْ وَالدَّارَقُطْنِيُّ وَغَيْرُهُمَا مُسْنَدًا، وَرَوَاهُ مَالِكٌ فِي المُوَطَّأِ مُرْسَلاً عَنْ عَمْرِو بْنِ يَحْيَى عَنْ أَبِيْهِ عَنِ النَّبِيِّ ﷺ فَأَسْقَطَ أَبَا سَعِيْدٍ، وَلَهُ طُرُقٌ يُقَوِّي بَعْضُهَا بَعْضًا.",
        "translation": "Dari Abu Sa’id Sa’ad bin Malik bin Sinan Al-Khudri Radhiyallahu ‘Anhu bahwa Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Tidak boleh membahayakan diri sendiri dan tidak boleh membahayakan orang lain.” (Hadits hasan, HR. Ibnu Majah no. 2340, Ad-Daraquthni no. 4540, dan selain keduanya dengan sanadnya, serta diriwayatkan pula oleh Malik dalam Al-Muwaththa` no. 31 secara mursal dari Amr bin Yahya dari ayahnya dari Nabi Shallallahu ‘Alaihi wa Sallam tanpa menyebutkan Abu Sa’id, tetapi ia memiliki banyak jalan periwayatan yang saling menguatkan satu sama lain)"
    },
    {
        "id": 33,
        "title": "Bukti Wajib Bagi Penuntut",
        "arabic": "عَنِ ابْنِ عَبَّاسٍ رَضِيَ اللهُ عَنْهُمَا، أَنَّ رَسُولَ اللهِ ﷺ قَالَ: «لَوْ يُعْطَى النَّاسُ بِدَعْوَاهُمْ، لَادَّعَى رِجَالٌ أَمْوَالَ قَوْمٍ وَدِمَاءَهُمْ، وَلَكِنِ البَيِّنَةُ عَلَى المُدَّعِي، وَاليَمِيْنُ عَلَى مَنْ أَنْكَرَ» حَدِيْثٌ حَسَنٌ رَوَاهُ البَيْهَقِيُّ هَكَذَا، بَعْضُهُ فِي الصَّحِيْحَيْنِ.",
        "translation": "Dari Ibnu ‘Abbas Radhiyallahu ‘Anhuma bahwa Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Seandainya setiap manusia dipenuhi tuntutannya, niscaya orang-orang akan menuntut harta suatu kaum dan darah mereka. Namun, bukti wajib bagi penuntut dan sumpah wajib bagi yang mengingkarinya.” (Hadits hasan, HR. Al-Baihaqi no. 21201 dalam Al-Kubro seperti ini, sebagiannya diriwayatkan dalam Shahihain, Al-Bukhari no. 4552 dan Muslim no. 1711)"
    },
    {
        "id": 34,
        "title": "Merubah Kemungkaran",
        "arabic": "عَنْ أَبِي سَعِيْدٍ الخُدْرِيِّ رَضِيَ اللهُ عَنْهُ، قَالَ: سَمِعْتُ رَسُولَ اللهِ ﷺ يَقُوْلُ: «مَنْ رَأَى مِنْكُمْ مُنْكَراً فَلْيُغَيِّرْهُ بِيَدِهِ، فَإِنْ لَمْ يَستَطِعْ فَبِلِسَانِهِ، فَإِنْ لَمْ يَستَطِعْ فَبِقَلْبِهِ وَذَلِكَ أَضْعَفُ الإِيْمَانِ» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu Sa’id Al-Khudri Radhiyallahu ‘Anhu, ia berkata: aku mendengar Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Barangsiapa dari kalian melihat kemungkaran, maka rubahlah dengan tangannya. Jika tidak bisa, maka dengan lisannya. Jika tidak bisa, maka dengan hatinya, dan itu merupakan selemah-lemah iman.” (HR. Muslim no. 49)"
    },
    {
        "id": 35,
        "title": "Hamba-Hamba Allah adalah Bersaudara",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ، قَالَ: قَالَ رَسُولُ اللهِ ﷺ: «لاَ تَحَاسَدُوا، وَلاَتَنَاجَشُوا، وَلاَ تَبَاغَضُوا، وَلاَ تَدَابَرُوا، وَلاَ يَبِعْ بَعْضُكُمْ عَلَى بَيْعِ بَعْضٍ، وَكُوْنُوا عِبَادَ اللهِ إِخوَاناً. المُسْلِمُ أَخُو المُسْلِمِ، لاَ يَظْلِمُهُ، وَلاَ يَخذُلُهُ، وَلَا يَكْذِبُهُ، وَلَايَحْقِرُهُ. التَّقْوَى هَاهُنَا -وَيُشِيْرُ إِلَى صَدْرِهِ ثَلاَثَ مَرَّاتٍ- بِحَسْبِ امْرِىءٍ مِنَ الشَّرِّ أَنْ يَحْقِرَ أَخَاهُ المُسْلِمَ. كُلُّ المُسْلِمِ عَلَى المُسْلِمِ حَرَامٌ: دَمُهُ وَمَالُهُ وَعِرْضُهُ» رَوَاهُ مُسْلِمٌ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu, ia berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Janganlah kalian saling mendengki, jangan saling tanajusy (menyakiti dalam jual beli), jangan saling marah, jangan saling membelakangi, dan jangan saling menjual barang yang sedang ditawar saudaranya. Jadilah hamba Allah yang bersaudara. Seorang Muslim menjadi saudara Muslim lainnya. Tidak boleh ia menzhaliminya, menelantarkannya, dan menghinanya. Takwa itu di sini –beliau memberi isyarat ke dadanya tiga kali–. Cukuplah berdosa seseorang jika ia menghina saudaranya yang Muslim. Setiap Muslim atas Muslim lainnya haram darahnya, hartanya, dan kehormatannya.’” (HR. Muslim no. 2564)"
    },
    {
        "id": 36,
        "title": "Keutamaan Akhlak dan Ilmu",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ، عَنِ النَّبِيِّ ﷺ قَالَ: «مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا، نَفَّسَ اللهُ عَنهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ القِيَامَةِ. وَمَنْ يَسَّرَ عَلَى مُعْسِرٍ، يَسَّرَ اللهُ عَلَيْهِ فِي الدُّنْيَا وَالآخِرَةِ. وَمَنْ سَتَرَ مُسْلِماً سَتَرَهُ اللهُ فِي الدُّنْيَا وَالآخِرَةِ. وَاللهُ في عَوْنِ العَبْدِ مَا كَانَ العَبْدُ فِي عَوْنِ أَخِيْهِ.\nوَمَنْ سَلَكَ طَرِيْقاً يَلْتَمِسُ فِيْهِ عِلْماً سَهَّلَ اللهُ لَهُ بِهِ طَرِيْقاً إِلَى الجَنَّةِ.\nوَمَا اجْتَمَعَ قَوْمٌ فِي بَيْتٍ مِنْ بُيُوْتِ اللهِ يَتْلُوْنَ كِتَابَ اللهِ وَيَتَدَارَسُوْنَهُ بَيْنَهُمْ إِلَّا نَزَلَتْ عَلَيْهِمُ السَّكِيْنَةُ، وَغَشِيَتْهُمُ الرَّحْمَةُ، وَحَفَّتْهُمُ الْمَلَائِكَةُ، وَذَكَرَهُمُ اللهُ فِيْمَنْ عِنْدَهُ، وَمَنْ بَطَّأَ بِهِ عَمَلُهُ لَمْ يُسْرِعْ بهِ نَسَبُهُ» رَوَاهُ مُسْلِمٌ بِهَذَا اللَّفْظِ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu, dari Nabi Shallallahu ‘Alaihi wa Sallam bersabda, “Barangsiapa yang menghilangkan kesusahan dari kesusahan-kesusahan dunia orang Mukmin, maka Allah akan menghilangkan kesusahan dari kesusahan-kesusahan hari Kiamat. Barangsiapa yang memberi kemudahan orang yang kesulitan (hutang), maka Allah akan memberi kemudahan baginya di dunia dan Akhirat. Allah senantiasa menolong hamba selagi dia menolong saudaranya. Barangsiapa yang menempuh perjalanan dalam rangka menuntut ilmu, maka Allah akan mudahkan baginya jalan menuju Surga. Tidaklah berkumpul sekelompok orang di salah satu rumah Allah untuk membaca Kitabullah dan saling mempelajarinya di antara mereka, melainkan akan turun kepada mereka ketenangan, rahmat meliputinya, para Malaikat mengelilinginya, dan Allah menyanjung namanya kepada Malaikat yang ada di sisi-Nya. Barangsiapa yang lambat amalnya, maka tidak akan bisa dikejar oleh nasabnya.” (HR. Muslim no. 2699 dengan lafazh ini)"
    },
    {
        "id": 37,
        "title": "Kebaikan dan Keburukan",
        "arabic": "عَنِ ابْنِ عَبَّاسٍ رَضِيَ اللهُ عَنْهُمَا، عَنِ النَّبِيِّ ﷺ -فِيْمَا يَرْوِي عَنْ رَبِّهِ تَبَارَكَ وَتَعَالَى-، قَالَ: «إِنَّ اللهَ كَتَبَ الحَسَنَاتِ وَالسَّيئَاتِ، ثُمَّ بَيَّنَ ذَلِكَ: فَمَنْ هَمَّ بِحَسَنَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللهُ عِنْدَهُ حَسَنَةً كَامِلَةً، وَإِنْ هَمَّ بِهَا فَعَمِلَهَا كَتَبَهَا اللهُ عِنْدَهُ عَشْرَ حَسَنَاتٍ إِلَى سَبْعِمِائَةِ ضِعْفٍ إِلَى أَضْعَافٍ كَثِيْرَةٍ.\nوَإِنْ هَمَّ بِسَيِّئَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللهُ عِنْدَهُ حَسَنَةً كَامِلَةً، وَإِنْ هَمَّ بِهَا فَعَمِلَهَا كَتَبَهَا اللهُ سَيِّئَةً وَاحِدَةً» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ فِي صَحِيْحَيْهِمَا بِهَذِهِ الحُرُوْفِ.",
        "translation": "Dari Ibnu ‘Abbas Radhiyallahu ‘Anhuma, dari Rasulullah Shallallahu ‘Alaihi wa Sallam tentang hadits yang beliau riwayatkan dari Rabb-nya Tabaraka wa Ta’ala. Beliau bersabda, “Sesungguhnya Allah menulis kebaikan-kebaikan dan keburukan-keburukan kemudian menjelaskannya. Barangsiapa yang berniat melakukan kebaikan lalu tidak mengerjakannya, maka Allah menulis itu di sisi-Nya sebagai satu kebaikan yang sempurna, dan jika dia berniat mengerjakan kebaikan lalu mengerjakannya, maka Allah menulis itu di sisi-Nya sebagai sepuluh kebaikan hingga tujuh ratus lipat hingga perlipatan yang banyak. Jika dia berniat melakukan keburukan lalu tidak jadi mengerjakannya, maka Allah menulis itu di sisi-Nya sebagai satu kebaikan yang sempurna, dan jika dia berniat melakukan keburukan lalu mengerjakannya, maka Allah menulis itu sebagai satu keburukan.” (HR. Al-Bukhari no. 6491 dan Muslim no. 131 di kitab shahih keduanya dengan lafazh ini)"
    },
    {
        "id": 38,
        "title": "Keutamaan Wali Allah",
        "arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ، قَالَ: قَالَ رَسُولُ اللهِ ﷺ : «إِنَّ اللهَ تَعَالَى قَالَ: مَنْ عَادَى لِي وَلِيّاً فَقَدْ آذَنْتُهُ بِالحَرْبِ. وَمَا تَقَرَّبَ إِلَيَّ عَبْدِيْ بِشَيْءٍ أَحَبَّ إِلَيَّ مِمَّا افْتَرَضْتُ عَلَيْهِ. وَمَا يَزَالُ عَبْدِيْ يَتَقَرَّبُ إِلَيَّ بِالنَّوَافِلِ حَتَّى أُحِبَّهُ، فَإِذَا أَحْبَبْتُهُ كُنْتُ سَمْعَهُ الَّذِي يَسْمَعُ بِهِ، وَبَصَرَهُ الَّذِي يُبْصِرُ بِهِ، وَيَدَهُ الَّتِي يَبْطِشُ بِهَا، وَرِجْلَهُ الَّتِي يَمْشِي بِهَا. وَلَئِنْ سَأَلَنِي لَأُعْطِيَنَّهُ، وَلَئِنْ اسْتَعَاذَنِي لَأُعِيْذَنَّهُ» رَوَاهُ البُخَارِيُّ.",
        "translation": "Dari Abu Hurairah Radhiyallahu ‘Anhu berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Sesungguhnya Allah Ta’ala berfirman, ‘Barangsiapa yang menyakiti waliku, maka Aku mengumumkan perang kepadanya. Tidaklah hamba-Ku mendekat kepada-Ku dengan sesuatu yang paling Aku cintai selain apa yang Aku wajibkan baginya. Hamba-Ku senantiasa mendekat kepada-Ku dengan amalan sunnah sehingga Aku mencintainya. Apabila aku telah mencintainya, Aku menjadi pendengarannya yang ia gunakan untuk mendengar, penglihatannya yang ia gunakan untuk melihat, tangannya yang ia gunakan untuk berbuat, dan kakinya yang ia gunakan untuk berjalan. Jika dia meminta kepadaku, pasti aku beri. Jika dia meminta perlindungan kepada-Ku pasti aku lindungi.’” (HR. Al-Bukhari no. 6502)"
    },
    {
        "id": 39,
        "title": "Tiga Hal yang Allah Maafkan",
        "arabic": "عَنِ ابْنِ عَبَّاسٍ رَضِيَ اللهُ عَنْهُمَا، أَنَّ رَسُولَ اللهِ ﷺ قَال: «إِنَّ اللهَ تَجَاوَزَ لِي عَنْ أُمَّتِي: الخَطَأَ وَالنِّسْيَانَ وَمَا اسْتُكْرِهُوا عَلَيْهِ» حَدِيْثٌ حَسَنٌ رَوَاهُ ابْنُ مَاجَهْ وَالبَيْهَقِيُّ وَغَيْرُهُمَا.",
        "translation": "Dari Ibnu ‘Abbas Radhiyallahu ‘Anhuma bahwa Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Sesungguhnya Allah mengampuni umatku untuku: kekeliruan, lupa, dan apa yang dipaksakan kepadanya.” (Hadits hasan, HR. Ibnu Majah no. 2045, Al-Baihaqi VII/356, dan selainnya)"
    },
    {
        "id": 40,
        "title": "Hiduplah Laksana Musafir",
        "arabic": "عَنِ ابْنِ عُمَرَ رَضِيَ اللهُ عَنْهُمَا، قَالَ: أَخَذَ رَسُولُ اللهِ ﷺ بِمَنْكِبَيَّ، فَقَالَ: «كُنْ فِي الدُّنْيَا كَأَنَّكَ غَرِيْبٌ أَوْ عَابِرُ سَبِيْلٍ»\nوَكَانَ ابْنُ عُمَرَ رَضِيَ اللهُ عَنْهُمَا يَقُوْلُ: إِذَا أَمْسَيْتَ فَلَا تَنْتَظِرِ الصَّبَاحَ، وَإِذَا أَصْبَحْتَ فَلَا تَنْتَظِرِ المَسَاءَ. وَخُذْ مِنْ صِحَّتِكَ لِمَرَضِكَ، وَمِنْ حَيَاتِكَ لِمَوْتِكَ. رَوَاهُ البُخَارِيُّ.",
        "translation": "Dari Ibnu ‘Umar Radhiyallahu ‘Anhuma berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam memegang kedua pundakku, lalu bersabda, “Jadilah engkau di dunia seperti orang asing atau seorang musafir.”\nIbnu ‘Umar Radhiyallahu ‘Anhuma berkata, “Jika kamu memasuki sore hari, maka jangan menunggu pagi hari. Jika kamu memasuki pagi hari, maka jangan menunggu sore hari. Manfaatkanlah sehatmu sebelum sakitmu, dan hidupmu sebelum matimu.” (HR. Al-Bukhari no. 6416)"
    },
    {
        "id": 41,
        "title": "Mengikuti Syariat adalah Tiang Keimanan",
        "arabic": "عَنْ أَبِي مُحَمَّدٍ عَبْدِ اللهِ بْنِ عَمْرِو بْنِ العَاصِ رَضِيَ اللهُ عَنْهُمَا، قَالَ: قَالَ رَسُولُ اللهِ ﷺ: «لاَيُؤْمِنُ أَحَدُكُمْ حَتَّى يَكُونَ هَوَاهُ تَبَعاً لِمَا جِئْتُ بِهِ» حَدِيْثٌ حَسَنٌ صَحِيْحٌ رُوِّيْنَاهُ فِي كِتَابِ الحُجَّةِ بِإِسْنَادٍ صَحِيْحٍ.",
        "translation": "Dari Abu Muhammad Abdullah bin ‘Amr bin ‘Ash Radhiyallahu ‘Anhuma berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Tidak beriman seorang dari kalian hingga hawa nafsunya mengikuti apa yang aku bawa.” (Hadits hasan shahih, kami meriwayatkannya dari kitab Al-Hujjah dengan sanad shahih)"
    },
    {
        "id": 42,
        "title": "Luasnya Ampunan Allah",
        "arabic": "عَنْ أَنَسٍ رَضِيَ اللهُ عَنْهُ، قَالَ: سَمِعْتُ رَسُولَ اللهِ ﷺ يَقُولُ: «قَالَ اللهُ تَعَالَى: يَا ابْنَ آدَمَ! إِنَّكَ مَا دَعَوتَنِي وَرَجَوْتَنِي غَفَرْتُ لَكَ عَلَى مَا كَانَ مِنْكَ وَلَا أُبَالِي. يَا ابْنَ آدَمَ! لَو بَلَغَتْ ذُنُوبُكَ عَنَانَ السَّمَاءِ ثُمَّ اسْتَغْفَرْتَنِي غَفَرْتُ لَكَ. يَا ابْنَ آدَمَ! إِنَّكَ لَو أَتَيْتَنِي بِقُرَابِ الأَرْضِ خَطَايَا ثُمَّ لَقِيْتَنِي لاَ تُشْرِكُ بِي شَيْئاً لَأَتَيْتُكَ بِقُرَابِهَا مَغْفِرَةً» رَوَاهُ التِّرْمِذِيُّ وَقَالَ: حَدِيْثٌ حَسَنٌ.",
        "translation": "Dari Anas bin Malik Radhiyallahu ‘Anhu, ia berkata: aku mendengar Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda, “Allah Tabarak wa Ta’ala berfirman, ‘Hai anak Adam! Sesungguhnya selagi engkau berdoa kepada-Ku dan berharap kepada-Ku, Aku ampuni dosa yang ada padamu dan aku tidak peduli. Hai anak Adam! Seandainya dosa-dosamu membumbung sepenuh langit, kemudian engkau meminta ampun kepada-Ku, pasti Aku ampuni. Hai anak Adam! Seandainya engkau mendatangi-Ku dengan dosa sepenuh bumi, kemudian engkau menemui-Ku tanpa menyekutukan-Ku dengan apapun, pasti Aku akan menemuimu dengan sepenuh bumi ampunan.” (HR. At-Tirmidzi no. 3540 dan berkata, “hadits hasan shahih.”)"
    },
    {
        "id": 43,
        "title": "Ilmu Warisan",
        "arabic": "عَنِ ابْنِ عَبَّاسٍ رَضِيَ اللهُ عَنْهُمَا، قَالَ: قَالَ رَسُولُ اللهِ ﷺ: «أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا أَبْقَتِ الفَرَائِضُ فَلِأَوْلَى رَجُلٍ ذَكَرٍ» خَرَّجَهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Ibnu Abbas Radhiyallahu ‘Anhuma, ia berkata: Rasulullah Shallallahu ‘Alaihi wa Sallam bersabda: “Berikanlah warisan kepada orang yang berhak. Jika masih ada sisa, maka diberikan kepada laki-laki yang paling dekat dengan mayit.” (HR. Al-Bukhari no. 6732 dan Muslim no. 1615)"
    },
    {
        "id": 44,
        "title": "Mahramnya Persusuan",
        "arabic": "عَنْ عَائِشَةَ رَضِيَ اللهُ عَنْهَا، عَنِ النَّبِيِّ ﷺ قَالَ: «الرَّضَاعَةُ تُحَرِّمُ مَا تُحَرِّمُ الْوِلاَدَةُ» رَوَاهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari ‘Aisyah Radhiyallahu ‘Anha, dari Nabi Shallallahu ‘Alaihi wa Sallam bersabda: “Susuan bisa menjadikan mahrom seperti halnya kelahiran.” (HR. Al-Bukhari no. 3105 dan Muslim no. 1444)"
    },
    {
        "id": 45,
        "title": "Perkara yang Diharamkan",
        "arabic": "عَنْ جَابِرِ بْنِ عَبْدِ اللهِ رَضِيَ اللهُ عَنْهُمَا، أَنَّهُ سَمِعَ رَسُولَ اللهِ ﷺ عَامَ الْفَتْحِ وَهُوَ بِمَكَّةَ يَقُولُ: «إِنَّ اللهَ وَرَسُولَهُ حَرَّمَ بَيْعَ الْخَمْرِ وَالْمَيْتَةِ وَالْخِنْزِيْرِ وَالأَصْنَامِ» فَقِيلَ: يَا رَسُولَ اللهِ، أَرَأَيْتَ شُحُومَ الْمَيْتَةِ، فَإِنَّهُ يُطْلَى بِهَا السُّفُنُ، وَيُدْهَنُ بِهَا الْجُلُودُ، وَيَسْتَصْبِحُ بِهَا النَّاسُ؟ قَالَ: «لاَ، هُوَ حَرَامٌ» ثُمَّ قَالَ رَسُولُ اللهِ ﷺ عِنْدَ ذَلِكَ: «قَاتَلَ اللهُ الْيَهُودَ، إنَّ اللهَ حَرَّمَ عَلَيْهِمُ الشُّحُومَ، فَأَجْمَلُوهُ، ثُمَّ بَاعُوهُ، فَأَكَلُوا ثَمَنَهُ» خَرَّجَهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Jabir bin Abdillah Radhiyallahu ‘Anhuma, dia mendengar Rasulullah Shallallahu ‘Alaihi wa Sallam berkata di Mekkah pada tahun Fathu Makkah: “Sesungguhnya Allah dan Rasul-Nya telah mengharamkan jual beli khamr, bangkai, babi dan berhala.” Dikatakan kepada beliau: “Wahai Rasulullah, bagaimana dengan lemak bangkai, karena ia digunakan untuk cat perahu-perahu, digunakan untuk meminyaki kulit, dan dimanfaatkan manusia untuk minyak lentera?” Rasulullah berkata: “Tidak boleh, ia haram.” Kemudian Rasulullah bersabda setelah itu: “Semoga Allah membinasakan Yahudi, sesungguhnya Allah telah mengharamkan atas mereka lemak bangkai kemudian mereka cairkan serta mereka jual dan mereka memakan hasil penjualannya.” (HR. Al-Bukhari no. 2236 dan Muslim no. 1581)"
    },
    {
        "id": 46,
        "title": "Setiap yang Memabukkan Haram",
        "arabic": "عَنْ أَبِي بُرْدَةَ، عَنْ أَبِيْهِ -أَبِي مُوْسَى الأَشْعَرِيِّ رَضِيَ اللهُ عَنْهُ- أَنَّ النَّبِيَّ ﷺ بَعَثَهُ إِلَى اليَمَنِ، فسَأَلَهُ عَنْ أَشْرَبَةٍ تُصْنَعُ بِهَا، فَقَالَ: «وَمَا هِيَ؟» قَالَ: البِتْعُ وَالمِرْزُ، -فَقِيْلَ لِأَبِي بُرْدَةَ: وما البِتْعُ؟ قَالَ: نَبِيْذُ العَسَلِ، وَالمِرْزُ نَبِيْذُ الشَّعِيْرِ­-، فَقَالَ: «كُلُّ مُسْكِرٍ حَرَامٌ» خَرَّجَهُ البُخَارِيُّ.",
        "translation": "Dari Abu Burdah dari bapaknya yakni Abu Musa Al- Asy’ari Radhiyallahu ‘Anhuma, bahwa Nabi Shallallahu ‘Alaihi wa Sallam mengutusnya ke Yaman dan ia bertanya kepada beliau tentang minuman yang dibuat di Yaman. Beliau bertanya: “Apa itu?” Abu Musa berkata: “Bit’u dan Mizru.” Ditanyakan kepada Abu Burdah: “Apa itu Bit’u?” Dia menjawab: “Saripati madu dan adapun Mizru adalah saripati gandum.” Maka Rasulullah bersabda: “Semua yang memabukkan adalah haram.” (HR. Al-Bukhari no. 4343)"
    },
    {
        "id": 47,
        "title": "Kaidah Kesehatan",
        "arabic": "عَنِ المِقْدَامِ بْنِ مَعْدِي كَرِبَ رَضِيَ اللهُ عَنْهُ، قَالَ: سَمِعْتُ رَسُولَ اللهِ ﷺ يَقُولُ: «مَا مَلَأَ آدَمِيٌّ وِعَاءً شَرًّا مِنْ بَطْنٍ، بِحَسْبِ ابْنِ آدَمَ أَكَلَاتٌ يُقِمْنَ صُلْبَهُ، فَإِنْ كَانَ لَا مَحَالَةَ، فَثُلُثٌ لِطَعَامِهِ، وَثُلُثٌ لِشَرَابِهِ، وَثُلُثٌ لِنَفَسِهِ» رَوَاهُ الإِمَامُ أَحْمَدُ وَالتِّرْمِذِيُّ وَابْنُ مَاجَهْ وَقَالَ التِّرْمِذِيُّ: حَدِيْثٌ حَسَنٌ.",
        "translation": "Dari Miqdam bin Ma’di Karib Radhiyallahu ‘Anhu: aku mendengar Rasulullah Shallallahu ‘Alaihi wa Sallam berkata: “Tidaklah seorang anak Adam memenuhi satu tempat yang lebih jelek dari (memenuhi) perutnya. Cukuplah bagi anak Adam makanan yang bisa menegakkan tulang punggungnya, jika harus (lebih dari itu) maka sepertiga untuk makanannya, sepertiga untuk minumannya dan sepertiga untuk nafasnya.” (HR. Imam Ahmad no. 17186, At-Tirmidzi no. 2380, Ibnu Majah no. 3349, dan At-Tirmidzi berkata: hadits hasan)"
    },
    {
        "id": 48,
        "title": "Sifat Munafik Tulen",
        "arabic": "عَنْ عَبْدِ اللهِ بْنِ عَمْرٍو رَضِيَ اللهُ عَنْهُمَا، عَنِ النَّبِيِّ ﷺ قَالَ: «أَرْبَعٌ مَنْ كُنَّ فِيهِ كَانَ مُنَافِقًا، وَإِنْ كَانَتْ خَصْلةٌ مِنْهُنَّ فِيهِ كَانَتْ فِيهِ خَصْلَةٌ مِنَ النِّفَاقِ حَتَّى يَدَعَهَا: مَنْ إِذَا حَدَّثَ كَذَبَ، وَإِذَا وَعَدَ أَخْلَفَ، وَإِذَا خَاصَمَ فَجَرَ، وَإِذَا عَاهَدَ غَدَرَ» خَرَّجَهُ البُخَارِيُّ وَمُسْلِمٌ.",
        "translation": "Dari Abdullah bin Amr Radhiyallahu ‘Anhu, dari Nabi Shallallahu ‘Alaihi wa Sallam bersabda: “Empat perkara, barangsiapa yang ada padanya keempat perkara tersebut maka ia munafik. Jika ada padanya satu diantara perangai tersebut berarti ada padanya satu perangai kemunafikan sampai mau meninggalkannya: (1) seorang yang jika bicara dusta, (2) jika membuat janji tidak menepatinya, (3) jika berselisih melampui batas, dan (4) jika melakukan perjanjian mengkhianatinya.” (HR. Al-Bukhari no. 34 dan Muslim no. 58)"
    },
    {
        "id": 49,
        "title": "Tawakkal Seperti Burung",
        "arabic": "عَنْ عُمَرَ بْنِ الخَطَّابِ رَضِيَ اللهُ عَنْهُ، عَنِ النَّبِيِّ ﷺ قَالَ: «لَوْ أَنَّكُمْ تَوَكَّلُوْنَ عَلَى اللهِ حَقَّ تَوَكُّلِهِ، لَرَزَقَكُمْ كَمَا يَرْزُقُ الطَّيرَ، تَغْدُو خِمَاصًا، وَتَرُوحُ بِطَانًا» رَوَاهُ الإِمَامُ أَحْمَدُ وَالتِّرْمِذِيُّ وَالنَّسَائِيُّ وَابْنُ مَاجَهْ، وَقَالَ التِّرْمِذِيُّ: حَدِيْثٌ صَحِيْحٌ",
        "translation": "Dari Umar bin Khaththab Radhiyallahu ‘Anhu, dari Nabi Shallallahu ‘Alaihi wa Sallam, beliau bersabda: “Jika kalian bertawakal kepada Allah dengan sebenar-benar tawakal niscaya Allah akan memberikan rezeki kepada kalian sebagaimana memberi rezeki kepada burung. Ia keluar di pagi hari dalam keadaan lapar dan pulang di sore hari dalam keadaan kenyang.” (HR. Imam Ahmad no. 205, At-Tirmidzi no. 2344, An-Nasai no. 11805, Ibnu Majah no. 4164, dan At-Tirmidzi berkata: hadits shahih)"
    },
    {
        "id": 50,
        "title": "Lisan Basah Berdzikir",
        "arabic": "عَنْ عَبْدِ اللهِ بْنِ بُسْرٍ رَضِيَ اللهُ عَنْهُ، قَالَ: أَتَى النَّبِيَّ ﷺ رَجُلٌ، فَقَالَ: يَا رَسُولَ اللهِ إِنَّ شَرَائِعَ الإِسْلاَمِ قَدْ كَثُرَتْ عَلَيْنَا، فَبَابٌ نَتَمَسَّكُ بِهِ جَامِعٌ؟ قَالَ: «لاَ يَزَالُ لِسَانُكَ رَطْبًا مِنْ ذِكْرِ اللهِ عَزَّ وَجَلَّ» خَرَّجَهُ الإِمَامُ أَحْمَدُ بِهَذَا اللَّفْظِ.",
        "translation": "Dari Abdullah bin Busr Radhiyallahu ‘Anhu, ia berkata: seorang laki-laki datang lalu berkata: “Wahai Rasulullah, syariat Islam itu terasa banyak bagiku, maka (ajarilah aku) satu bab (ilmu) yang menyeluruh yang akan kupegang teguh?” Beliau bersabda: “Lisanmu terus-menerus berdzikir kepada Allah Azza wa Jalla.” (HR. Imam Ahmad no. 17680 dengan lafazh ini)"
    }
]